# permissions for end users to view managedcontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: managedcontrolplane-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k3s-cpaas
    app.kubernetes.io/part-of: k3s-cpaas
    app.kubernetes.io/managed-by: kustomize
  name: managedcontrolplane-viewer-role
rules:
- apiGroups:
  - managedcontrolplane.k3s.control-plane.io
  resources:
  - managedcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - managedcontrolplane.k3s.control-plane.io
  resources:
  - managedcontrolplanes/status
  verbs:
  - get
